version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    env_file:
      - ./envs/.env.dev
    volumes:
      # Hot reload - bind mount source code
      - ./src:/app/src:ro
      - ./prisma:/app/prisma:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./nest-cli.json:/app/nest-cli.json:ro
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    environment:
      POSTGRES_DB: nodeduasapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_dev_data:
